# Generated by Django 4.2.6 on 2023-11-12 15:00

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parentCategory",
            field=models.ForeignKey(
                default=Product.models.setDefault,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="Product.productcategory",
            ),
        ),
    ]
