# Generated by Django 4.2.6 on 2023-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_productcategory_parentcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
