# Generated by Django 4.2.6 on 2023-11-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_product_brand"),
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Puschase",
            new_name="Purchase",
        ),
    ]
