# Generated by Django 4.2.6 on 2023-11-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_return_rename_puschase_purchase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="product_id",
            new_name="product",
        ),
    ]
