# Generated by Django 4.2.6 on 2023-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0003_rename_product_id_sales_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="quantity_available",
            field=models.IntegerField(default=0),
        ),
    ]
