# Generated by Django 4.2.6 on 2023-11-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0004_alter_inventory_quantity_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="purchase_id",
            new_name="purchase",
        ),
    ]
